
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertNotNull;

import javax.swing.filechooser.FileNameExtensionFilter;

import org.junit.Test;

public class ConwayGameOfLifeTest {
	ConwayGameOfLife tester;
	String fileName = "gameOfLife_input.txt";
	int[][] initialDummy = 
		{
			{ 1, 0, 0, 1, 0, 1 },
			{ 0,1 , 0, 0, 1, 1 },
			{ 0, 0, 0, 0, 0, 0 },
			{ 1, 1, 0, 0, 1, 0 },
			{ 0, 0, 0, 0, 0, 0 },
			{ 1, 0, 0, 1, 0, 1 },
			{ 0, 1, 0, 0, 1, 1 },
			{ 0, 0, 0, 0, 0, 0 }
		};
	
//	@BeforeClass
//    public static void setUpBeforeClass() throws Exception {   
//        Properties props = new Properties();
//        InputStream fileIn = ConwayGameOfLifeTest.class.getClassLoader().getResourceAsStream("gameOfLife_input.txt");
//        		//props_.getClass().getResourceAsStream("/gameOfLife_input.txt");
//        **props.load(fileIn);**
//       
//    }

	@Test
	public void test() {
		tester = new ConwayGameOfLife();
		
		inputTest();
		
		int[][] nextStateDummy = 
			{
				{ 0, 0, 0, 0, 0, 1 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 1, 1, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 0, 0 },
				{ 1, 1, 0, 0, 1, 0 },
				{ 0, 0, 0, 0, 0, 1 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 0, 0 }
			};
		

		int[][] state3StateDummy = 
			{
				{ 0, 0, 0, 0, 0, 0 }, 
				{ 0, 0, 0, 0, 0, 0 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 1, 1 },
				{ 0, 0, 0, 0, 0, 0 }
			};
		
		calculateNextStateTest(nextStateDummy);
		findKthStateTest(3, state3StateDummy);
	} 
	
	/*
	 * This method will test whether the input() generates the same 2D array 
	 * as initialDummy[][] from the input file.
	 */
	
	void inputTest(){
		System.out.println("Inside inputTest()");
		int[][] initial = tester.makeInput(fileName);
		assertNotNull(initial);
		assertArrayEquals(initial, initialDummy);
		System.out.println("inputTest() Done!");
		
	}
	
	/*
	 * I am passing nextStateDummy array which will be tested against the 
	 * array generated by calculateNextStateTest(...) method.
	 */
	
	void calculateNextStateTest(int[][] nextStateDummy){
		System.out.println("Inside calculateNextStateTest()");
		int[][] nextState = tester.calculateNextState(initialDummy);
		assertNotNull(nextState);
		
		assertArrayEquals(nextState, nextStateDummy);
		
		System.out.println("calculateNextStateTest() Done!");
	}
	
	/*
	 * I am passing state3StateDummy array which will be tested against the 
	 * array generated by findKthState(...) method.
	 */
	void findKthStateTest(int k , int[][] state3StateDummy){
		System.out.println("Inside findKthStateTest()");
		int[][] kthState = tester.findKthState(k, initialDummy);
		assertNotNull(kthState);
		
		assertArrayEquals(kthState, state3StateDummy);
		System.out.println("findKthStateTest() Done!");
	}
	
	public static void main(String[] args){
//		test();
		new ConwayGameOfLifeTest().test();
	}

}
